### ISSUE TITLE
Issues with indexer in Druid chart

### ISSUE THREAD

**Issue by adelrizaev** [wiremind/wiremind-helm-charts#472]
Druid indexer hangs when injestion task starts.

In the logs of the druid broker i see such error log:

2024-04-26T16:03:13,898 ERROR [FilteredHttpServerInventoryView-3] org.apache.druid.server.coordination.ChangeRequestHttpSyncer - failed to get sync response from [http://druid-indexer-default-0:8100/_1714146848195]. Return code [0], Reason: [null]
org.jboss.netty.channel.ChannelException: Faulty channel in resource pool
	at org.apache.druid.java.util.http.client.NettyHttpClient.go(NettyHttpClient.java:134) ~[druid-processing-26.0.0.jar:26.0.0]
	at org.apache.druid.server.coordination.ChangeRequestHttpSyncer.sync(ChangeRequestHttpSyncer.java:218) ~[druid-server-26.0.0.jar:26.0.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: java.net.ConnectException: Connection refused: druid-indexer-default-0/10.43.63.44:8100
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777) ~[?:?]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152) ~[netty-3.10.6.Final.jar:?]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105) ~[netty-3.10.6.Final.jar:?]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79) ~[netty-3.10.6.Final.jar:?]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) ~[netty-3.10.6.Final.jar:?]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42) ~[netty-3.10.6.Final.jar:?]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) ~[netty-3.10.6.Final.jar:?]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) ~[netty-3.10.6.Final.jar:?]
	... 3 more

The strange is, there are two services exposed

![Screenshot 2024-04-26 at 18 07 38](https://github.com/wiremind/wiremind-helm-charts/assets/141411808/c742d8c4-a96d-48dd-b09f-979029d0b803)

**Comment by ssidorenko** [comment]
Did you ever solve this?

**Comment by desaintmartin** [comment]
We don't reproduce, still running several Druids in production. Closing since there is no clear reproducible path.
